# Generated by Django 4.2.2 on 2023-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TextData',
        ),
    ]
