# Generated by Django 4.2.2 on 2023-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWA', '0002_ngram_delete_textdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ngram',
        ),
    ]
